language: node_js
node_js:
  - "14"

install:
  - npm install
  - npm run build
  
deploy:
  provider: npm
  skip_cleanup: true
  email: "casino.online@novomatic-tech.com"
  api_key: $AUTH_TOKEN
  on:
    tags: true
